### ISSUE TITLE
Can't compile with  Windows SDK version 10.0.22621.0 - MSVC 14.29.30133

### ISSUE THREAD

**Issue by LilianKBayro** [open-license-manager/licensecc#158]
Hello,

At the end of the build, I get the following error :
```

license_generator_lib.lib(command_line-parser.obj) : error LNK2019: unresolved external symbol "public: static unsigned int const boost::program_options::options_description::m_default_line_length" (?m_default_line_length@options_description@program_options@boost@@2IB) referenced in function "void __cdecl license::initializeProject(class boost::program_options::basic_parsed_options<char> const &,class boost:: program_options::variables_map &,char const * *,class boost::program_options::options_description const &)" (?initializeProject@license@@YAXAEBV?$basic_parsed_options@D@program_options@boost@@AEAVvariables_map@34@PEAPEBDAEBVoptions_description@34@@Z) [C:\Users\Lilian\licensecc\build\extern\license-generator\src\license_generator\lccgen.vcxproj]
C:\Users\Lilian\licensecc\build\extern\license-generator\src\license_generator\Release\lccgen.exe : fatal error LNK1120: 2 unresolved externals [C:\Users\Lilian\licensecc\build\extern\license-generator\src\license_generator\lccgen.vcxproj]


```

any ideas ? Should I use an older version of MSVC ?

**Comment by LilianKBayro** [comment]
I indeed use Boost 1.71

**Comment by LilianKBayro** [comment]
Problem solved using Visual Studio 2019 (older version)
